[build-system]
requires = [
"setuptools>=61.0",
"numpy==1.23.5",
"pandas==1.5.3",
"biopython==1.78",
"dssp==3.0.0",
"scikit-learn==1.2.2",
"scipy==1.10.1",
"matplotlib==3.6.2",
"seaborn==0.12.2",
"cython==0.29.32",
"ticc==0.1.4"
"vmd-python"
]
build-backend = "setuptools.build_meta"
[project]
name = "APPSquared"
version = "0.0.1"
authors = [
  { name="Nicole Paterson, Nicholas Kovacs", email="qxa4@cdc.gov" },
]
description = "A Pipeline to Characterize Influenza Antigenic Proteins"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/nicolepaterson/APPSquared"
"Bug Tracker" = "https://github.com/nicolepaterson/APPSquared/issues"
